server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: springboot
    static_configs:
      - targets:
          - localhost
        labels:
          job: springboot
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}
      - json:
        expressions:
          level: level
      - regex:
          expression: '.*(INFO|ERROR).*'
      - match:
          selector: '{job="springboot"}'
          stages:
            - output:
                source: message
    relabel_configs:
      - source_labels: [container]
        regex: "/springboot-app"         # <<< Match your container name
        action: keep                     # <<< Keep only this container's logs