server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: springboot
    static_configs:
      - targets:
          - localhost
        labels:
          job: springboot
          container: springboot-app
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - docker: {}
      - regex:
          expression: '.*(INFO|ERROR).*'
      - output:
          source: message   # ✅ this is a single stage, not nested under `match`

    relabel_configs:
      - source_labels: [container]
        regex: springboot-app
        action: keep
